# Generated by Django 3.1.6 on 2021-02-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='radar',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.JSONField(default='{}'),
        ),
    ]
